### ISSUE TITLE
一个可能会删除所有文件的 bug

### ISSUE THREAD

**Issue by sihuan** [kaiakz/rsync-os#5]
详见 #4 
这个 bug 会导致在需要有文件被清理时，**总会**执行

```go
fname := string(localList[0].Path)
err := r.storage.Delete(fname, localList[0].Mode)
```
`localList[0]` 往往是 `.` 目录，这在某些储存后端的实现中将会递归删除当前所有文件。

**Comment by kaiakz** [comment]
谢谢你的提醒：），我认为的确会存在这个问题。

因为filelist一般情况下会包括"."这一项，我需要先去看一下原版rsync里面怎么处理这种情况。

这个项目设计上是想要简化rsync部分的职责，把文件处理等复杂的东西交给storage处理。现阶段其实还并不安全，例如对方发送了"../aVirus"可能会把文件写到某个的地方。

**Comment by sihuan** [comment]
你再仔细看一下那个 for 循环🤔
要删除的文件是 `localList[deleteList[i]]` 而不是 `localList[i]`

**Comment by kaiakz** [comment]
嗯，是的。我原来想写的是`localList[deleteList[i]]`，但我写错了，变成了删除filelist前len(deleteList)项了。

**Comment by kaiakz** [comment]
已合并你的PR，谢谢！
